# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroConectados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'registro de conexión',
                'verbose_name_plural': 'registro de conexiones',
            },
        ),
    ]
