# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conectados_Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Registro Compras',
                'verbose_name': 'Registro Compra',
            },
        ),
        migrations.DeleteModel(
            name='Descarga',
        ),
        migrations.DeleteModel(
            name='RegistroCompras',
        ),
        migrations.DeleteModel(
            name='Top',
        ),
    ]
