# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(max_length=30)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=5)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('name', models.CharField(max_length=26)),
                ('guild_name', models.CharField(max_length=26, null=True)),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('ranking', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
