# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('real_name', models.CharField(blank=True, max_length=16, null=True)),
                ('social_id', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('coins', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('availdt', models.DateTimeField(db_column='availDt', default='2020-01-01T00:00:00')),
                ('token_expire', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account',
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
