# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
